"""Add mid_fail/backlog/eligible_for_endsem/uploaded_file_id to marks

Revision ID: 52bda18e1b8b
Revises: 7ab2590aa8d0
Create Date: 2025-09-26 16:23:53.164830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52bda18e1b8b'
down_revision = '7ab2590aa8d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mid_fail', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('backlog', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('eligible_for_endsem', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_file_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'uploaded_files', ['uploaded_file_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('uploaded_file_id')
        batch_op.drop_column('eligible_for_endsem')
        batch_op.drop_column('backlog')
        batch_op.drop_column('mid_fail')

    # ### end Alembic commands ###
