"""add students subjects marks uploadedfiles

Revision ID: 6d4c9a7387d8
Revises: d956cc2b8979
Create Date: 2025-09-14 12:27:29.864185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4c9a7387d8'
down_revision = 'd956cc2b8979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pin')
    )
    op.create_table('subjects',
    sa.Column('sub_code', sa.String(length=50), nullable=False),
    sa.Column('sub_name', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sub_code')
    )
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('sub_code', sa.String(length=50), nullable=False),
    sa.Column('mid1', sa.Float(), nullable=True),
    sa.Column('mid2', sa.Float(), nullable=True),
    sa.Column('internal', sa.Float(), nullable=True),
    sa.Column('end_sem', sa.Float(), nullable=True),
    sa.Column('attendance', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('subject_score', sa.Float(), nullable=True),
    sa.Column('risk', sa.String(length=10), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['sub_code'], ['subjects.sub_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'sub_code', 'semester', name='uix_student_subject_sem')
    )
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('exam_type', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_on', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_files')
    op.drop_table('marks')
    op.drop_table('subjects')
    op.drop_table('students')
    # ### end Alembic commands ###
