"""add Institution table

Revision ID: 7ab2590aa8d0
Revises: 84f8591d02bb
Create Date: 2025-09-15 05:59:59.632998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ab2590aa8d0'
down_revision = '84f8591d02bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_year', sa.Integer(), nullable=False))
        batch_op.drop_column('year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('exam_year')

    # ### end Alembic commands ###
