"""add Institution table

Revision ID: 84f8591d02bb
Revises: 6d4c9a7387d8
Create Date: 2025-09-15 05:48:32.360267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f8591d02bb'
down_revision = '6d4c9a7387d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institution')
    # ### end Alembic commands ###
